<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.1.0" />
    <ProjectReference Include="..\ATM.Application\ATM.Application.csproj" />
    <PackageReference Include="Iot.Device.Bindings" Version="3.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.1" />
    <PackageReference Include="System.Device.Gpio" Version="3.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net6.0-windows10.0.17763.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
